### PR TITLE
Fixed security and ownership of PAK archives

### LINKED ISSUE #1: Support distributing PAK archives
The PAK archive format, by default,  sets the user to be JENKINS and "OOOO". This should be changed to another user and "NUNU" security.

### PR DESCRIPTION
**Pull request by rsbeckerca**
Fixes #1

CLA: Permission is granted by the author to the ITUGLIB team to use these modifications.

Signed-off-by: Randall S. Becker <rsbecker@nexbridge.com>

### CODE REVIEW

File: RepackagePak.groovy [hunk 1]
```diff
@@ -25,31 +25,28 @@ class RepackagePak extends AbstractRepackage {
    }
 
    public void chown(File target) {
-      String command = "sudo gtacl -c 'fup /IN [#MYTERM]/ give jenktemp.*,255,255'";
+      String command = "sh give.sh SUPER.SUPER";
```
Comment (rsbeckerca) [inline RepackagePak.groovy:28]: This is where the attribute for package content ownership is set.

File: RepackagePak.groovy [hunk 2]
```diff
@@ -25,31 +25,28 @@ class RepackagePak extends AbstractRepackage {
...
-         /* System.exit(result); */
+         println taskName+'give reported '+result;
+         System.exit(result);
       }
    }
 
    public void chgrp(File target) {
-      String command = "sudo gtacl -c 'fup /IN [#MYTERM]/ secure jenktemp.*,'"+
-         '"NUNU"';
+      String command = "sh secure.sh NCNC";
```
Comment (rsbeckerca) [inline RepackagePak.groovy:41]: There is where the security for package contents is set.
